// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpRO2egPKJsDiZo9gMp9XJ5CDU52c1DFk',
    appId: '1:532794097721:web:1cfc58dd4f9334df98cde8',
    messagingSenderId: '532794097721',
    projectId: 'flutterapp-a1b25',
    authDomain: 'flutterapp-a1b25.firebaseapp.com',
    storageBucket: 'flutterapp-a1b25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkw0IHKjqzhzi95pr-M31g2LJjYz3JAI',
    appId: '1:532794097721:android:c40b1ce11dcbf1a198cde8',
    messagingSenderId: '532794097721',
    projectId: 'flutterapp-a1b25',
    storageBucket: 'flutterapp-a1b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPRT1oVT0xRgkzAHEjYrmbz3xvS_jyNXI',
    appId: '1:532794097721:ios:75af20a45ed62ebe98cde8',
    messagingSenderId: '532794097721',
    projectId: 'flutterapp-a1b25',
    storageBucket: 'flutterapp-a1b25.appspot.com',
    iosClientId: '532794097721-nofk30fvbmsu6firtcqvi72sl5ganah9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sense2quit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPRT1oVT0xRgkzAHEjYrmbz3xvS_jyNXI',
    appId: '1:532794097721:ios:22773d0d47161d7498cde8',
    messagingSenderId: '532794097721',
    projectId: 'flutterapp-a1b25',
    storageBucket: 'flutterapp-a1b25.appspot.com',
    iosClientId: '532794097721-9nd1pf0nioq5no0qlut37pt50avva09u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sense2quit.RunnerTests',
  );
}
